### ISSUE TITLE
TNG name

### ISSUE THREAD

**Issue by damassi** [getify/TNG-Hooks#23]
Wondering why the decision was made to make `TNG` all caps? It's feels slightly unidiomatic, requires holding down the shift key, etc. I saw there was the [name bikeshedding](https://github.com/getify/TNG-Hooks/issues/7) issue, but just wondering what the reasoning was and if it's really necessary? This is such a cool idea and it seems like a worthy aim to keep things as vanilla as possible and slightly more literal. Like what is "tng"? Why not `"makeHooks"` or `import { useState } from 'fn-hooks'`? etc. To invoke everything with "TNG" doesn't seem meaningful language-wise.

**Comment by getify** [comment]
The TNG (pronounced "ting") name has a few meanings/reasons:

* It started as "totally not globals" -- a nod to the idea that it's like having global storage but not-global  because its in closures

* I planned a talk to introduce TNG, called "State Track: The Next Generation" (a nod to star trek TNG, etc)

* It's hard to get unique names on npm these days, especially in the realm of react/hooks/etc. TNG is a nice unique moniker.

----

My thought was, if people didn't like using the name TNG, they can always call it some other name. In npm: `var { TNG: coolHooks, .. } = require("tng-hooks");`. In the browser, "window.coolHooks = window.TNG;`.

**Comment by getify** [comment]
> Why not "makeHooks" or import { useState } from 'fn-hooks'? etc. To invoke everything with "TNG" doesn't seem meaningful language-wise.

I don't have TNG exporting itself as an ES6 module yet, but the various hooks, like `useState(..)`, etc, are in fact individual "exports" on the API of this lib. You don't say `TNG.useState(..)`, you just say `useState(..)` (just like in React).

The only time you use the `TNG` name is for the function that creates the wrapped/hooked functions (aka "Articulated Functions"). And as I said above, if you don't like saying `myFunc = TNG(myFunc);`, you can rename TNG to whatever you prefer, like `setupHooks(..)` or whatever.

**Comment by damassi** [comment]
Ok this makes sense! thank you for explaining 👍
